### ISSUE TITLE
RN New Architecture: TypeError: this.nativeUtils().setKeepDeviceAwake is not a function (it is undefined)

### ISSUE THREAD

**Issue by itsmnjn** [daily-co/react-native-daily-js#63]
# Expected behavior

The Daily.co React Native SDK (`@daily-co/react-native-daily-js`) should work with React Native's New Architecture (Fabric) when enabled in Expo SDK 52.

# Describe the bug (unexpected behavior)

When using the Daily.co SDK with React Native's New Architecture enabled in Expo 52, calling `Daily.createCallObject()` and attempting to join a call fails with the following error:

`TypeError: this.nativeUtils().setKeepDeviceAwake is not a function (it is undefined)`

The call works correctly when New Architecture is disabled, confirming this is specifically a New Architecture compatibility issue.

# Steps to reproduce

1. Create a new Expo 52 project
2. Enable New Architecture by setting `"newArchEnabled": true` in app.json
3. Install and configure @daily-co/react-native-daily-js
4. Attempt to join a Daily call
5. Observe the setKeepDeviceAwake error

# System information 

* Device: iOS device
* OS: iOS 18.1.1
* Framework: Expo SDK 52
* React Native New Architecture: Enabled
* @daily-co/react-native-daily-js: [0.70.0]

# Additional context

This appears to be a compatibility issue between the Daily.co native modules and React Native's New Architecture (Fabric). The error occurs because the native module bridge is not properly configured for the new architecture, specifically the `setKeepDeviceAwake` method.

The issue can be temporarily worked around by disabling New Architecture (`"newArchEnabled": false`), but this isn't a long-term solution as New Architecture is becoming the standard.

Request: Please update the react-native-daily-js library to support React Native's New Architecture.

**Comment by alexandreaugus** [comment]
Same issue

**Comment by filipi87** [comment]
Hi @itsmnjn, 

Our SDK is still not targeting the new architecture.

But, what is the version of RN that you are using ? 

With version 0.76 RN added a compatibility layer, which includes an automatic interoperability layer to enable backward compatibility with libraries that are still not targeting the new architecture.

I am planning to update our Expo Demo to use the latest RN version together with Expo to make sure it works. 

But let me know in case you get there first.

Another option is to disable the new architecture. To do that, you need to remove "newArchEnabled": true from the app.json file.

**Comment by alexandreaugus** [comment]
@filipi87 I'm using React Native 0.77.0, and while disabling the new arch works as a temporary workaround, we'll eventually need to migrate

**Comment by RwNoob** [comment]
How to solve this problem, now my react native version is 0.78

**Comment by Shempaiii** [comment]
Up

**Comment by Shempaiii** [comment]
How @alexandreaugus ?

**Comment by alexandreaugus** [comment]
@Shempaiii 
on app.json
`{ expo: { newArchEnabled: false } ...other properties }`

Then on top of Podfile
`
ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
`

However, this is a workaround, we need the daily.co team to update their SDK as we can't rely on a quick fix for production apps

**Comment by Shempaiii** [comment]
> [@Shempaiii](https://github.com/Shempaiii) on app.json `{ expo: { newArchEnabled: false } ...other properties }`
> 
> Then on top of Podfile `ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'`
> 
> However, this is a workaround, we need the daily.co team to update their SDK as we can't rely on a quick fix for production apps

@alexandreaugus , if not Expo, React Native CLI?

**Comment by Shempaiii** [comment]
> > [@Shempaiii](https://github.com/Shempaiii) on app.json `{ expo: { newArchEnabled: false } ...other properties }`
> > Then on top of Podfile `ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'`
> > However, this is a workaround, we need the daily.co team to update their SDK as we can't rely on a quick fix for production apps
> 
> [@alexandreaugus](https://github.com/alexandreaugus) , if not Expo, React Native CLI?
>>> [teopalva](https://github.com/teopalva) mentioned this [5 days ago](https://github.com/daily-co/react-native-daily-js/issues/63#event-2167412333)
[WIP: Add Support for React Native New Architecture (TurboModule) #64](https://github.com/daily-co/react-native-daily-js/pull/64)

@teopalva, still not working. I've targeted the feature branch containing the expected fix

<img width="822" alt="Image" src="https://github.com/user-attachments/assets/10a60f44-4027-4f68-a037-94bf26fe6a0d" />
<img width="610" alt="Image" src="https://github.com/user-attachments/assets/b45d1f51-a680-4232-ad83-5e554c7ec1f7" />
![Image](https://github.com/user-attachments/assets/05bd2b37-1c42-4c7b-82fc-78f3500ea3ba)

**Comment by Shempaiii** [comment]
@teopalva, now working. Thanks!

**Comment by bouwerp** [comment]
@filipi87 any progress on supporting the new architecture?

**Comment by filipi87** [comment]
Hi, we are going to prioritize adding support for the new architecture this quarter. I’ll let you know as soon as it’s released. Thank you all for the support!

**Comment by bouwerp** [comment]
@filipi87 Amazing, thanks so much! Looking forward to it.

**Comment by bouwerp** [comment]
@filipi87 just checking in whether there has been any movement on this?

**Comment by filipi87** [comment]
Hi, it should be possible to use `react-native-daily-js` in apps with the new architecture enabled starting with the next release.

**Comment by Gautham495** [comment]
I am getting the same error.

How to fix this?

**Comment by jensellfors** [comment]
I ended up patching this library, removing the call `setKeepDeviceAwake`. This way I got it working with new architecture. We are using this expo lib instead to control keep awake https://docs.expo.dev/versions/latest/sdk/keep-awake/

**Comment by filipi87** [comment]
Hi, early next week we are going to release a new version of `react-native-daily-js` with this fixed. 

Until there, the way to workaround this is to disable the new architecture, as mentioned [here](https://github.com/daily-co/react-native-daily-js/issues/63#issuecomment-2717098178).

**Comment by Gautham495** [comment]
@filipi87 - Thank you so much.

Do let me know, once it is fixed.

**Comment by filipi87** [comment]
Hi, we released `react-native-daily-js` version **0.77.0** today.

You can see [the daily-expo-demo](https://github.com/daily-demos/daily-expo-demo) running with the new architecture enabled and using Expo 53.

Thank you all, and let me know if you need any help.

**Comment by daman-talkshoplive** [comment]
@filipi87 
`RN 0.75.5` & `react-native-daily-js: 0.77.0`

On Android joining room still throws `TypeError: this.nativeUtils().setAudioMode`

**Comment by filipi87** [comment]
Hi @daman-talkshoplive , You need to use RN 0.76.9 or above.

**Comment by Gautham495** [comment]
@filipi87 - It worked well in iOS - Thanks a lot.

**Comment by daman-talkshoplive** [comment]
@filipi87 It's still the same problem on `RN 0.76.9` Android with `newArchEnabled`.

`joinRoom [TypeError: this.nativeUtils().setAudioMode is not a function (it is undefined)]`

**Comment by filipi87** [comment]
Hi @daman-talkshoplive, I thought I had tested in the past with React Native 0.76.9, but it turns out I had actually tested with RN 0.77.2, using our [daily-expo-demo](https://github.com/daily-demos/daily-expo-demo/). So while it should work with RN 0.76.9, I haven’t personally tested that version yet with the new architecture enabled.

Currently, both of our demos are using RN 0.79.3, and they’re working well with Expo 53 and the new architecture enabled.
- https://github.com/daily-demos/daily-expo-demo/
- https://github.com/daily-co/react-native-daily-js-playground

If upgrading is an option, I’d recommend using the latest versions. If it is not an option, I can try running that specific version in one of our demos to see if I can reproduce the issue.

Also, within the demo project, I’ve created this helper script:
- https://github.com/daily-demos/daily-expo-demo/blob/main/scripts/clear_and_rebuild.sh
   - It ensures everything is properly cleared and rebuilt whenever I toggle something important, like enabling or disabling the new architecture, or changing the expo version or any other native library.

**Comment by daman-talkshoplive** [comment]
@filipi87 Thank you! It's a bare RN project. I'll try upgrading to 0.77.2+

**Comment by filipi87** [comment]
We have recently migrated our playground app, from bare React Native to Expo, and it is now much easier to maintain. So, if that's an option, perhaps it would be worth considering. 🙂

**Comment by daman-talkshoplive** [comment]
With large number of dependencies, unfortunately Expo is not an option for us.

**Comment by Gautham495** [comment]
@filipi87 - It works well on Android as well.

Thanks for your efforts.
